language:
  - node_js
node_js: 8
services:
  - mongodb
sudo: true
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-4.8 g++-4.8
  - sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libavahi-compat-libdnssd-dev # npm install mdns
  - export CXX="g++-4.8" CC="gcc-4.8"
git:
  depth: 1
